### ISSUE TITLE
Unable to join tables if there are more than 1000 rows

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#165]
Code to reproduce:
```
import numpy as np
import modin.pandas as pd
import modin.config as cfg

cfg.IsExperimental.put(True)
cfg.Engine.put("Native")
cfg.StorageFormat.put("Hdk")

data = np.random.randint(0, 100, size=(1001, 99))
df = pd.DataFrame(data)
df["new"] = pd.Series(list(range(len(df))))
print(df)
```

Error message:
```
modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py:76: in _executeRelAlgJson
    res = rel_alg_executor.execute()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   RuntimeError: Hash join failed, reason(s): Could not build a 1-to-1 correspondence for columns involved in equijoin | Cannot join on rowid | Cannot fall back to loop join for non-trivial inner table size

_sql.pyx:103: RuntimeError
```

**Comment by ienkovich** [comment]
While this particular case can be executed by increasing the loop join limit, the problem here is in using `rowid` virtual column which is not supported by hash join. In Modin, we use `rowid` for the default index and it might be a common situation when this index is used for joins. So, we should consider supporting `rowid` in hash joins.

What concerns me here is that the semantics of the test seem to assume outer join here, which is not supported at all (right now Modin uses inner join here, but this is most probably incorrect). So, supporting `rowid` in hash joins without outer join support wouldn't give us enough functionality to cover this and similar cases in Modin.

**Comment by AndreyPavlenko** [comment]
The following cases are probably also related to this issue. In all these cases inner join by index is performed.

```
data = {"A": []}
df = pd.DataFrame(data)
df["B"] = pd.Series([1, 2, 3])
assert len(df) == 3
```
E       assert 0 == 3

```
data = {"a": [1, 2, 3, 4]}
index = pandas.to_datetime(["2020-02-06", "2020-02-06", "2020-02-22", "2020-03-26"])
df = pd.DataFrame(data, index=index)
df["b"] = pd.Series(np.arange(4))
print(df)
```
E   RuntimeError: Cannot compare between TIMESTAMP[ns] and INT64

**Comment by ienkovich** [comment]
> E RuntimeError: Cannot compare between TIMESTAMP[ns] and INT64

In this case, one frame uses an integer index and another one uses datetime index. I wonder what is the actual semantics of the series assignment then. Is it actually equal to `df["b"] = None`? Looks like it should be handled on Modin's side (just assign NULL to the resulting column or add proper casts for join).

**Comment by ienkovich** [comment]
BTW, looks like the assignment to the column is actually a left join. So, we don't need an outer join for that, but shouldn't use an inner join either.

```
>>> df = pandas.DataFrame({"a": [1, 2, 3, 4]}, index=[2,3,4,5])
>>> df["b"] = pandas.Series(np.arange(4))
>>> print(df)
   a    b
2  1  2.0
3  2  3.0
4  3  NaN
5  4  NaN
```
So, the original issue can be resolved by proper support of `rowid` column in hash joins.
